//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _420_476.Projet.Session.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int ID { get; set; }
        public int MembreID { get; set; }
        public string Nom { get; set; }
        public string Race { get; set; }
        public Nullable<int> Age { get; set; }
        public string Besoins { get; set; }
        public string Etat { get; set; }
    
        public virtual Membre Membre { get; set; }
    }
}
