//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _420_476.Projet.Session.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int ID { get; set; }
        public int MembreID { get; set; }
        public string Nom { get; set; }
        public string Race { get; set; }
        public Nullable<int> Age { get; set; }
        public string Besoins { get; set; }
        public string Etat { get; set; }
    
        public virtual Membre Membre { get; set; }
    }
}
