//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _420_476.Projet.Session.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ID { get; set; }
        public int OffrantID { get; set; }
        public string Label { get; set; }
        public string Type { get; set; }
        public decimal Prix { get; set; }
    
        public virtual Offrant Offrant { get; set; }
    }
}
