//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _420_476.Projet.Session.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesRating
    {
        public int ID { get; set; }
        public int ServiceID { get; set; }
        public int MembreID { get; set; }
        public int OffrantID { get; set; }
        public Nullable<decimal> Note { get; set; }
        public string Text { get; set; }
    
        public virtual Membre Membre { get; set; }
        public virtual Offrant Offrant { get; set; }
        public virtual Service Service { get; set; }
    }
}
